### ISSUE TITLE
has_concept() selector doesn't work since pkgdown 2.0.4

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#2129] opened 2022-06-14 15:44 UTC
Reprex repo:

https://github.com/Bisaloo/reprex_pkgdown_concept

It works fine with pkgdown 2.0.3 (installed with `remotes::install_github("r-lib/pkgdown@v2.0.3")` but fails with pkgdown devel or 2.0.4 with the following error:

> Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: hello
In addition: Warning message:
Unknown or uninitialised column: `concepts`.

**Comment by maelle** [comment] 2022-06-14 16:28
Duplicate of #2126

**Comment by maelle** [comment] 2022-06-14 16:28
Thanks for the reprex and report @Bisaloo!

**Closed by maelle** 2022-06-14 16:28 UTC
