### ISSUE TITLE
rhandsontable not displaying properly in vignettes/articles

### ISSUE THREAD

**Issue by john-harrold** [r-lib/pkgdown#1736] opened 2021-07-17 14:52 UTC
I'm trying to get pkgdown to display tables created by the `rhandsontable` package. To create an example I cloned the foofactors repository (this is mentioned in the [R Packages Book](https://r-pkgs.org/whole-game.html)) and created a simple vignette. When I render the vignette in RMarkdown it loos like this:

![image](https://user-images.githubusercontent.com/3170004/126040631-d97b7718-c29e-4f27-9c01-20d826ba9c2e.png)

Now when I build the site with pkgdown it looks like this:
![image](https://user-images.githubusercontent.com/3170004/126040648-5a276b97-0ede-4939-a837-0df950e90dd1.png)

You can see the result on [Github Pages](https://john-harrold.github.io/foofactors/articles/Example.html).

The forked repository is here: https://github.com/john-harrold/foofactors

<details>
And this is the output of my session_info:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6          compiler_4.0.2      pillar_1.6.0       
 [4] later_1.1.0.1       tools_4.0.2         digest_0.6.27      
 [7] jsonlite_1.7.1      evaluate_0.14       memoise_2.0.0      
[10] lifecycle_1.0.0     tibble_3.1.1        pkgconfig_2.0.3    
[13] rlang_0.4.10        shiny_1.5.0         cli_2.5.0          
[16] rstudioapi_0.13     yaml_2.2.1          pkgdown_1.6.1      
[19] xfun_0.23           fastmap_1.1.0       withr_2.4.2        
[22] knitr_1.33          desc_1.2.0          fs_1.5.0           
[25] htmlwidgets_1.5.2   vctrs_0.3.8         rprojroot_2.0.2    
[28] glue_1.4.2          R6_2.5.0            processx_3.4.5     
[31] fansi_0.4.2         rmarkdown_2.8       callr_3.5.1        
[34] purrr_0.3.4         magrittr_2.0.1      ps_1.5.0           
[37] promises_1.1.1      htmltools_0.5.0     ellipsis_0.3.2     
[40] usethis_2.0.1       assertthat_0.2.1    rhandsontable_0.3.7
[43] mime_0.9            xtable_1.8-4        httpuv_1.5.4       
[46] utf8_1.2.1          cachem_1.0.4        crayon_1.4.1
```

</details>

**Comment by dmurdoch** [comment] 2021-07-17 15:35
This looks like issue #1689

**Comment by dmurdoch** [comment] 2021-07-17 15:37
Forgot to mention:  it's fixed by #1719.

**Comment by john-harrold** [comment] 2021-07-17 18:18
I'm having a little trouble understanding the fix. Are you saying that I just need to install the version of pkgdown from github, build the site with `pkgdown::build_site()` and that should do it?

**Comment by dmurdoch** [comment] 2021-07-17 20:20
Current versions on CRAN (and for `pkgdown`, the master branch on Github) don't currently handle html widgets.  You can install ones that do using

    remotes::install_github(c("r-lib/downlit",
                          "dmurdoch/pkgdown@issue1689",
                          "dmurdoch/htmlwidgets@rglpatch")) 

The `pkgdown` you install is newer than CRAN's, but misses all changes to the master branch since June 4.  If you really need the most recent stuff, you'll need a more complicated install:  install the master branch, and merge in the changes from issue #1689.

**Comment by john-harrold** [comment] 2021-07-17 20:39
Thank you Duncan. If I did this correctly (I just installed the three packages in that remotes::install_github command) it didn't seem to work for me. I've included the output of sessionInfo in case if it can help identify something I might have messed up. 

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13    knitr_1.33         magrittr_2.0.1    
 [4] R6_2.5.0           rlang_0.4.11       fastmap_1.1.0     
 [7] fansi_0.5.0        tools_4.0.2        xfun_0.24         
[10] utf8_1.2.1         withr_2.4.2        remotes_2.2.0     
[13] htmltools_0.5.1.1  ellipsis_0.3.2     yaml_2.2.1        
[16] digest_0.6.27      rprojroot_2.0.2    tibble_3.1.2      
[19] lifecycle_1.0.0    pkgdown_1.6.1.9001 crayon_1.4.1      
[22] processx_3.5.2     callr_3.7.0        purrr_0.3.4       
[25] ps_1.6.0           vctrs_0.3.8        fs_1.5.0          
[28] curl_4.3.2         memoise_2.0.0      glue_1.4.2        
[31] cachem_1.0.5       evaluate_0.14      rmarkdown_2.9     
[34] compiler_4.0.2     pillar_1.6.1       desc_1.3.0        
[37] pkgconfig_2.0.3  
```

**Comment by dmurdoch** [comment] 2021-07-17 20:42
In that case it looks like it's not the same problem as #1689.

**Comment by john-harrold** [comment] 2021-07-17 23:14
Thanks for trying to help. I appreciate it.

**Comment by hadley** [comment] 2021-09-21 18:09
Closing as duplicate of #1689

**Comment by john-harrold** [comment] 2021-09-21 22:54
> Closing as duplicate of #1689

I'm sorry, I'm confused. I went through the fixes that @dmurdoch proposed that were supposed to fix this and they did not. He was under the impression that because those failed to address the issue, this is a different issue than #1689. Was his diagnosis incorrect?

**Comment by hadley** [comment] 2021-09-22 12:27
Sorry, misread @dmurdoch's comment, and missed the "not" 😞

**Comment by hadley** [comment] 2021-09-22 18:09
Ok, this is for **articles** not reference pages, and the code flows through in totally different way.

**Comment by hadley** [comment] 2021-09-22 18:14
Or was this always about articles? Now I'm confused 😢

**Comment by john-harrold** [comment] 2021-09-22 21:49
Sorry for the confusion. My issue is that rhandsontable objects are not displaying properly in articles. 

This example article shows what I'm getting. There is a box there, but it's empty:

https://john-harrold.github.io/foofactors/articles/Example.html

**Comment by hadley** [comment] 2021-09-27 13:01
I can confirm rhandsontable doesn't work (in either examples or articles) after the latest changes. But as far as I can tell the html is correctly injected into the page, along with all the needed dependencies. So this suggests that something in the rhandsontable css/js conflicts with the pkgdown css/js and you'd need to work with the package author to figure out what the problem is.

**Closed by hadley** 2021-09-27 13:01 UTC
Labels: bug, articles :writing_hand:
