### ISSUE TITLE
crayon/cli output does not render correctly when comment=""

### ISSUE THREAD

**Issue by gmbecker** [r-lib/pkgdown#2196] opened 2022-09-19 22:42 UTC
I believe this is a still-alive case of #1843 

When the `comment` chunk option is set to `""`, we (still) see the eroneous escaped ansi color codes in output.

To reproduce, set the `comment` option in `vignettes/test/rendering.Rmd` to `""`, and then build the articles for pkgdown itself. When you view the produced html page for that vignette, you will see:

![Screen Shot 2022-09-19 at 3 40 55 PM](https://user-images.githubusercontent.com/908721/191131968-01371de2-e7cd-41da-8e96-784510150254.png)

Which you do not see with the current value of `comment="#>"`

**Comment by maelle** [comment] 2022-11-25 11:04
I've just realized this is a duplicate of #1965, sorry and thanks for reporting!

**Comment by maelle** [comment] 2022-11-25 11:04
Duplicate of #1965

**Closed by maelle** 2022-11-25 11:04 UTC
