### ISSUE TITLE
UTF-8 Encoding in README

### ISSUE THREAD

**Issue by adamhsparks** [r-lib/pkgdown#1295] opened 2020-04-09 00:27 UTC
I've seen other threads indicating issues with UTF-8 and umlauts in citation files and author lists, but I'm seeing it in the README with umlauts and single quote characters, _e.g._, GrÃ¼nwald in place of Grünwald and â in place of a stylised '.

You can see the rendered HTML from README.Rmd here: https://openplantpathology.github.io/Reproducibility_in_Plant_Pathology/

This happens locally using macOS and using the GitHub pkgdown actions from r-lib, https://github.com/openplantpathology/Reproducibility_in_Plant_Pathology/blob/master/.github/workflows/pkgdown.yml.

I've set the encoding to UTF-8 in DESCRIPTION, https://github.com/openplantpathology/Reproducibility_in_Plant_Pathology/blob/master/DESCRIPTION

I don't recall this having been an issue in the past, I just noticed it today.

**Comment by hadley** [comment] 2020-04-09 00:35
Duplicate of #1294

**Closed by hadley** 2020-04-09 00:35 UTC
