### ISSUE TITLE
If package resides in repo sub-directory, source link is not correct

### ISSUE THREAD

**Issue by DavorJ** [r-lib/pkgdown#1152] opened 2019-09-22 19:45 UTC
I followed [this](https://pkgdown.r-lib.org/articles/linking.html) guide to set up linking.

In case the package resides in the sub-directory of a github repository, then linking of source files is not correct. 

![image](https://user-images.githubusercontent.com/4161918/65393473-3e76bf00-dd81-11e9-9ead-516c97ac1ed7.png)

Cf. [here](https://dov-vlaanderen.github.io/groundwater-logger-validation/gwloggeR/docs/articles/gwloggeR.html).

It is always linked to the root of the repository, and not to the subfolder.

In case of the example:
* Wrong: https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/vignettes/gwloggeR.Rmd
* Correct: https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/gwloggeR/vignettes/gwloggeR.Rmd

In the [DESCRIPTION](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/gwloggeR/DESCRIPTION) file the correct URL is supplied.

All other links seem to work correctly.

Using: pkgdown_1.4.1

**Comment by StrikerRUS** [comment] 2019-09-28 12:00
Hi @DavorJ !

We ended up using the following JS hack to overcome this issue: https://github.com/microsoft/LightGBM/blob/master/R-package/pkgdown/extra.js.

**Comment by hadley** [comment] 2020-03-11 20:03
Duplicate of new #1238

**Closed by hadley** 2020-03-11 20:03 UTC
Labels: feature, linking :paperclip:
