### ISSUE TITLE
pkgdown does not recognize non-ASCII characters when deploying to Travis

### ISSUE THREAD

**Issue by kguidonimartins** [r-lib/pkgdown#1287] opened 2020-04-02 22:59 UTC
We are trying to deploy our package [site](https://liibre.github.io/coronabr/index.html) using Travis with the 'UTF-8' encoding. When we build our site locally using `pkgdown::build_site()`, our *.md files (README, CONTRIB. AND ABOUT) are rendered correctly. However, when we deploy the site, pkgdown does not recognize non-ASCII characters from *.md files. The articles in the vignette folder are deployed with the correct encoding. We tried different solutions, for example, including a .Rprofile with `options(encoding = 'UTF-8')` via Makefile just for deployment, but it also doesn't work.

**Below is how our home page is rendered after deployment:**

![image](https://user-images.githubusercontent.com/8163542/78307213-cea97400-751b-11ea-8658-6651ae4397c1.png)

**And how our articles are rendered after deployment:**

![image](https://user-images.githubusercontent.com/8163542/78307232-d832dc00-751b-11ea-9525-56eb9c3d6483.png)

**Here is the travis.yml we are using:**

```yml
language: r

sudo: false

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-gnome-pt language-pack-pt-base
  - sudo apt-get -y install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libgdal-dev bwidget libgdal-dev libgdal1-dev libgeos-dev libgeos++-dev libgsl0-dev libproj-dev libspatialite-dev netcdf-bin libgmp3-dev libudunits2-dev cargo

cache: packages

script: make all

env:
    global:
        - LANG=pt_BR.UTF-8
        - LC_ALL=pt_BR.UTF-8

matrix:
  include:
  - r: devel
  - r: release
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
      local-dir: docs
      on:
        branch: master

after_success:
  - Rscript -e 'devtools::install()'

r_packages:
  - brazilmaps
  - dplyr
  - plyr
  - fs
  - ggplot2
  - glue
  - httr
  - janitor
  - jsonlite
  - magrittr
  - readr
  - rlang
  - rvest
  - sf
  - stringr
  - tidyr
  - tmap
  - xml2
  - gganimate
  - devtools
  - knitr
  - rgdal
  - gifski
  - pkgdown
  - webshot
  - rmarkdown
  - remotes

os:
  - linux
```

How can we make this work?

**Comment by hadley** [comment] 2020-04-03 11:47
Could you please start by providing a minimal reproducible example? The easiest way to do that here would be to create a package with only a readme that contains only a problematic character.

**Comment by jayhesselberth** [comment] 2020-04-03 11:52
There are some instructions on package reprexes on the contributing guide: https://pkgdown.r-lib.org/dev/CONTRIBUTING.html

**Comment by wkmor1** [comment] 2020-04-03 13:51
possibly due to https://github.com/r-lib/xml2/issues/293

**Comment by kguidonimartins** [comment] 2020-04-03 16:30
Sure! Here is the [link](https://github.com/kguidonimartins/brokennonascii) of the temp package and my reprex. I don't know if it's my browser settings, but your [contributing](https://pkgdown.r-lib.org/dev/CONTRIBUTING.html) file also has problems with non-ASCII.


``` r
library(usethis)
library(pkgdown)

link_readme <- "https://raw.githubusercontent.com/liibre/coronabr/master/README.Rmd"

tmp_pkg <- file.path(".", "brokennonascii")

usethis::create_package(path = tmp_pkg, open = FALSE)
#> ✔ Creating './brokennonascii/'
#> ✔ Setting active project to '/tmp/RtmpIUGkfX/reprex5e32b59e237/brokennonascii'
#> ✔ Creating 'R/'
#> ✔ Writing 'DESCRIPTION'
#> Package: brokennonascii
#> Title: What the Package Does (One Line, Title Case)
#> Version: 0.0.0.9000
#> Authors@R (parsed):
#>     * First Last <first.last@example.com> [aut, cre] (<https://orcid.org/YOUR-ORCID-ID>)
#> Description: What the package does (one paragraph).
#> License: What license it uses
#> Encoding: UTF-8
#> LazyData: true
#> ✔ Writing 'NAMESPACE'
#> ✔ Setting active project to '<no active project>'

download.file(url = link_readme, destfile = paste0(tmp_pkg, "/README.md"))

pkgdown::build_site(tmp_pkg, new_process = FALSE, preview = FALSE)
#> ── Installing package into temporary library ─────────────────────────────────────────────
#> ══ Building pkgdown site ═════════════════════════════════════════════════════════════════
#> Reading from: '/tmp/RtmpIUGkfX/reprex5e32b59e237/brokennonascii'
#> Writing to:   '/tmp/RtmpIUGkfX/reprex5e32b59e237/brokennonascii/docs'
#> ── Initialising site ─────────────────────────────────────────────────────────────────────
#> Copying '../../../../home/karlo/R/x86_64-pc-linux-gnu-library/3.6/pkgdown/assets/bootstrap-toc.css' to 'bootstrap-toc.css'
#> Copying '../../../../home/karlo/R/x86_64-pc-linux-gnu-library/3.6/pkgdown/assets/bootstrap-toc.js' to 'bootstrap-toc.js'
#> Copying '../../../../home/karlo/R/x86_64-pc-linux-gnu-library/3.6/pkgdown/assets/docsearch.css' to 'docsearch.css'
#> Copying '../../../../home/karlo/R/x86_64-pc-linux-gnu-library/3.6/pkgdown/assets/docsearch.js' to 'docsearch.js'
#> Copying '../../../../home/karlo/R/x86_64-pc-linux-gnu-library/3.6/pkgdown/assets/link.svg' to 'link.svg'
#> Copying '../../../../home/karlo/R/x86_64-pc-linux-gnu-library/3.6/pkgdown/assets/pkgdown.css' to 'pkgdown.css'
#> Copying '../../../../home/karlo/R/x86_64-pc-linux-gnu-library/3.6/pkgdown/assets/pkgdown.js' to 'pkgdown.js'
#> Writing '404.html'
#> ── Building home ─────────────────────────────────────────────────────────────────────────
#> Writing 'authors.html'
#> ── Building function reference ───────────────────────────────────────────────────────────
#> Writing 'reference/index.html'
#> ══ DONE ══════════════════════════════════════════════════════════════════════════════════
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Ubuntu 16.04.6 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_US                       
#>  collate  en_US.UTF-8                 
#>  ctype    pt_BR.UTF-8                 
#>  tz       America/Sao_Paulo           
#>  date     2020-04-03                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package        * version    date       lib source        
#>    assertthat       0.2.1      2019-03-21 [1] CRAN (R 3.6.1)
#>    backports        1.1.5      2019-10-02 [1] CRAN (R 3.6.1)
#>  R brokennonascii * 0.0.0.9000 <NA>       [?] <NA>          
#>    callr            3.4.3      2020-03-28 [1] CRAN (R 3.6.3)
#>    cli              2.0.2      2020-02-28 [1] CRAN (R 3.6.3)
#>    clisymbols       1.2.0      2017-05-21 [1] CRAN (R 3.6.1)
#>    crayon           1.3.4      2017-09-16 [1] CRAN (R 3.6.1)
#>    curl             4.3        2019-12-02 [1] CRAN (R 3.6.1)
#>    desc             1.2.0      2018-05-01 [1] CRAN (R 3.6.1)
#>    devtools         2.2.2      2020-02-17 [1] CRAN (R 3.6.3)
#>    digest           0.6.25     2020-02-23 [1] CRAN (R 3.6.3)
#>    ellipsis         0.3.0      2019-09-20 [1] CRAN (R 3.6.1)
#>    evaluate         0.14       2019-05-28 [1] CRAN (R 3.6.1)
#>    fansi            0.4.1      2020-01-08 [1] CRAN (R 3.6.2)
#>    fs               1.4.0      2020-03-31 [1] CRAN (R 3.6.3)
#>    glue             1.3.2      2020-03-12 [1] CRAN (R 3.6.3)
#>    highr            0.8        2019-03-20 [1] CRAN (R 3.6.1)
#>    htmltools        0.4.0      2019-10-04 [1] CRAN (R 3.6.1)
#>    httr             1.4.1      2019-08-05 [1] CRAN (R 3.6.1)
#>    knitr            1.28       2020-02-06 [1] CRAN (R 3.6.3)
#>    lifecycle        0.2.0      2020-03-06 [1] CRAN (R 3.6.3)
#>    magrittr         1.5        2014-11-22 [1] CRAN (R 3.6.1)
#>    MASS             7.3-51.5   2019-12-20 [4] CRAN (R 3.6.2)
#>    memoise          1.1.0      2017-04-21 [1] CRAN (R 3.6.1)
#>    pillar           1.4.3      2019-12-20 [1] CRAN (R 3.6.2)
#>    pkgbuild         1.0.6      2019-10-09 [1] CRAN (R 3.6.1)
#>    pkgconfig        2.0.3      2019-09-22 [1] CRAN (R 3.6.1)
#>    pkgdown        * 1.5.0      2020-03-25 [1] CRAN (R 3.6.3)
#>    pkgload          1.0.2      2018-10-29 [1] CRAN (R 3.6.1)
#>    prettyunits      1.1.1      2020-01-24 [1] CRAN (R 3.6.2)
#>    processx         3.4.2      2020-02-09 [1] CRAN (R 3.6.3)
#>    ps               1.3.2      2020-02-13 [1] CRAN (R 3.6.3)
#>    purrr            0.3.3      2019-10-18 [1] CRAN (R 3.6.1)
#>    R6               2.4.1      2019-11-12 [1] CRAN (R 3.6.1)
#>    Rcpp             1.0.4      2020-03-17 [1] CRAN (R 3.6.3)
#>    remotes          2.1.1      2020-02-15 [1] CRAN (R 3.6.3)
#>    rlang            0.4.5      2020-03-01 [1] CRAN (R 3.6.3)
#>    rmarkdown        2.1        2020-01-20 [1] CRAN (R 3.6.2)
#>    rprojroot        1.3-2      2018-01-03 [1] CRAN (R 3.6.1)
#>    rstudioapi       0.11       2020-02-07 [1] CRAN (R 3.6.3)
#>    sessioninfo      1.1.1      2018-11-05 [1] CRAN (R 3.6.1)
#>    stringi          1.4.6      2020-02-17 [1] CRAN (R 3.6.3)
#>    stringr          1.4.0      2019-02-10 [1] CRAN (R 3.6.1)
#>    testthat         2.3.2      2020-03-02 [1] CRAN (R 3.6.3)
#>    tibble           3.0.0      2020-03-30 [1] CRAN (R 3.6.3)
#>    usethis        * 1.5.1      2019-07-04 [1] CRAN (R 3.6.1)
#>    vctrs            0.2.4      2020-03-10 [1] CRAN (R 3.6.3)
#>    whisker          0.4        2019-08-28 [1] CRAN (R 3.6.1)
#>    withr            2.1.2      2018-03-15 [1] CRAN (R 3.6.1)
#>    xfun             0.12       2020-01-13 [1] CRAN (R 3.6.2)
#>    xml2             1.3.0      2020-04-01 [1] CRAN (R 3.6.3)
#>    yaml             2.2.1      2020-02-01 [1] CRAN (R 3.6.2)
#> 
#> [1] /home/karlo/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
#> 
#>  R ── Package was removed from disk.
```

</details>

**Comment by hadley** [comment] 2020-04-03 20:37
Locally, this worked fine for me with xml2 1.2.5, but had the problem with 1.3.0, so https://github.com/r-lib/xml2/issues/293 is almost certainly the root cause.

**Comment by jayhesselberth** [comment] 2020-04-04 21:51
This is fixed by https://github.com/r-lib/xml2/commit/654385789de3ac2ee08d05555a32147eb8a12457, which will be in a forthcoming patch release.

For now you can install the dev version of xml2 with `remotes::install_github("r-lib/xml2")`

**Closed by jayhesselberth** 2020-04-04 21:51 UTC
Labels: bug
