### ISSUE TITLE
Open hosted pkgdown vignettes url

### ISSUE THREAD

**Issue by schloerke** [r-lib/pkgdown#1342] opened 2020-06-05 02:48 UTC
https://pkgdown.r-lib.org/articles/pkgdown.html#articles talks about hosting vignettes only within the `pkgdown` website.  This is great as it reduces the submitted package size and installation time.

It would be great to be able to still call some form of `vignette(name, package = pkg)` that would redirect to the `pkgdown` website articles. (The function could even fall back on `utils::vignette(name, package = pkg)` to view local vignettes.)

I have implemented this specifically for `GGally`, but it would be great if this interface was unified across packages.

`vig_ggally(name)`: https://github.com/ggobi/ggally/pull/367/files#diff-a2fb4aeef14197c9a34de26d66559ca9

If this function was made, I don't think I would submit any vignettes to CRAN.

**Comment by hadley** [comment] 2020-06-11 14:54
Duplicate of #1247

**Closed by hadley** 2020-06-11 14:54 UTC
