### ISSUE TITLE
request: article argument to build_articles()

### ISSUE THREAD

**Issue by kbenoit** [r-lib/pkgdown#489] opened 2018-01-13 07:46 UTC
It would be great to have an argument to `build_articles()` that allowed specifying which should be built. I am using a pkgdown site with lots of articles, and it takes a long time to rebuild all of them when I only change a single one.

The site: http://docs.quanteda.io see "Quick Start", "Examples", "Replications".

Great package!!

**Comment by hadley** [comment] 2018-02-20 21:32
Duplicate of #382

**Closed by hadley** 2018-02-20 21:32 UTC
