### ISSUE TITLE
Adding `\pkg{PKG}` in a function title produces extra/bad HTML

### ISSUE THREAD

**Issue by schloerke** [r-lib/pkgdown#1344] opened 2020-06-08 14:44 UTC
Reprex:

```r
#' Text \pkg{pkgdown} text
#' 
test_fn <- function() {}
```

Output:

<img width="476" alt="Screen Shot 2020-06-08 at 10 42 01 AM" src="https://user-images.githubusercontent.com/93231/84043849-cd118780-a974-11ea-87a0-302921be55fc.png">

If `\pkg` is not allowed in the title, please let me know!

**Comment by jayhesselberth** [comment] 2020-06-08 16:36
Is `\pkg{}` a roxygen tag? It's not specifically recognized by pkgdown. What were you hoping to see?

``` r
library(pkgdown)

rd2html("\\bold{x}")
#> [1] "<b>x</b>"

rd2html("\\pkg{x}")
#> [1] "<span class=\"pkg\">x</span>"
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Bisaloo** [comment] 2020-06-09 08:53
`\pkg{}` is a Rd tag. It's listed in the "Writing R extensions" manual: https://cran.r-project.org/doc/manuals/R-exts.html#Marking-text

> \pkg{package_name}
>
 >   Indicate the name of an R package. LaTeX-like.

**Comment by hadley** [comment] 2020-06-11 15:01
@schloerke can you please make a reprex following https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md#rd-translation ?

**Comment by hadley** [comment] 2020-06-11 15:02
Actually this is probably the same as #1318, and something specifically related to the title.

**Comment by hadley** [comment] 2020-07-18 13:34
Duplicate of #1318 — the problem is that we're not stripping html from `<title>`

**Closed by hadley** 2020-07-18 13:34 UTC
