### ISSUE TITLE
warning for malformed badges

### ISSUE THREAD

**Issue by yonicd** [r-lib/pkgdown#849] opened 2018-10-27 19:04 UTC
https://github.com/r-lib/pkgdown/blob/2c59c8f7c1ff6cf2c091c6efc96954e77a131782/R/html-tweak.R#L257

i recently had a malformed badge out of a few and it was being created ok in the md, but pkgdown is more sensitive to any malformation in the badges, like looking for `!nzchar` characters outside of tags. In this case pkgdown throws out all the badges from the render of the `index.html` and they show up a the top of the html instead of on the sidebar.

That is one of a few checks done on the badges

```r
# No paragraph
  if (length(x) == 0) {
    return(character())
  }

  # No non-whitespace characters outside of tags
  if (xml2::xml_text(x, trim = TRUE) != "") {
    return(character())
  }

  badges <- xml2::xml_children(x)
  if (length(badges) == 0) {
    return(character())
  }

  if (!all(xml2::xml_name(badges) %in% "a")) {
    return(character())
  }
```

If possible can a warning be added to which badge is malformed, and character() is returned, to give the user better direction what is wrong and where to fix it? Also can only the malformed badge be removed from a vector of badges (if there is more than one)? ie `if(length(xml2::xml_children(x))>1)` and a boolean returns `TRUE`, then drop the problem child and process the rest.

below is an example of what I had (now [fixed](https://raw.githubusercontent.com/metrumresearchgroup/texPreview/master/README.md)) 

```
[![CRAN\_Status\_Badge](https://www.r-pkg.org/badges/version/texPreview)](https://cran.r-project.org/package=texPreview)
[![Project Status: Active - The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/0.1.0/active.svg)](http://www.repostatus.org/#active) 
![downloads](http://cranlogs.r-pkg.org/badges/texPreview)[![Travis-CI Build Status](https://travis-ci.org/metrumresearchgroup/texPreview.svg?branch=master)](https://travis-ci.org/metrumresearchgroup/texPreview)
[![Coverage Status](https://img.shields.io/codecov/c/github/metrumresearchgroup/texPreview/master.svg)](https://codecov.io/github/metrumresearchgroup/texPreview?branch=master)
[![Covrpage Summary](https://img.shields.io/badge/covrpage-Last_Build_2018_10_24-brightgreen.svg)](http://tinyurl.com/ybkr8fsu)
```

**Comment by hadley** [comment] 2018-11-12 23:30
I think this is probably out of scope for now; the problem is we don't have a good model for determining if you have a block of (possibly slightly malformed) badges, or you have a paragraph of text with linked images.

**Closed by hadley** 2018-11-12 23:30 UTC
Labels: feature, home :house:

**Comment by yonicd** [comment] 2018-11-13 00:30
Even a warning would help to give a hint to why the badges are being ignored on home builds. It took a while to understand what was the problem.
