### ISSUE TITLE
Including functions with similar rd/man pages in references 

### ISSUE THREAD

**Issue by Blackglade** [r-lib/pkgdown#986] opened 2019-03-09 20:38 UTC
Currently I am specifying the types of functions to use with my _pkgdown.yaml config file. Several functions in a library I'm working on have the same man page generated by roxygen2. I however want to include these functions in separate categories on the references page. For example, given the following functions:

```
#' @rdname foo_bar
foo <- function(){}

#' @rdname foo_bar
bar <- function(){}
```
Specifying my yaml config file like this:
```
reference:
- title: Group A
  contents:
  - foo
- title: Group B
  contents:
  - bar
```
 yields two separate sections... but BOTH sections include the foo() and bar() function despite individually defining them only because they are linking to the same man/rd page

**Comment by jayhesselberth** [comment] 2019-03-09 21:14
That's by design, the `@rdname` and `title` reference sections have the same connotation. I think you'll have to remove the `@rdname` if you want to split these functions across two reference sections.

**Comment by Blackglade** [comment] 2019-03-11 14:54
Darn okay. I was hoping was hoping for more exact control over my references page with _pkgdown.yaml. This design essentially causes several functions to appear multiple times because of how interlinked they are. Is there anyway to prevent this?

**Comment by jemus42** [comment] 2019-03-12 20:49
You'd need to split your .Rd's or cross-reference them in a different way. I'm currently having the same headache. Possible candidates for my next experiments are `@describeIn` and the `man-roxygen` template thing (`@template` ? It's used heavily in plyr, see https://github.com/hadley/plyr/tree/master/man-roxygen) in case I split stuff up even more.

Anyway, while I wish pkgdown could be more independent from the existing `.Rd` structure, I don't think that's a realistic goal in the short term, so we'll have to tweak our existing documentation structure and then just let pkgdown do it's thing.

**Comment by jayhesselberth** [comment] 2019-04-14 13:06
pkgdown makes strong assumptions about Rd structure, and that's not likely to change.

Closing this for now.

**Closed by jayhesselberth** 2019-04-14 13:06 UTC

**Comment by Polkas** [comment] 2022-03-01 14:10
Hey, I have the same problem after 3 years. Does it still valid that there should be no control how the reference is built. Current state does not give any flexibility and force us to updated the roxygen2. Thanks for consideration.
