### ISSUE TITLE
Add toggle between development and released version websites

### ISSUE THREAD

**Issue by mccarthy-m-g** [r-lib/pkgdown#2392] opened 2024-01-27 00:12 UTC
## Summary

It would be nice if there was a convenient way to toggle between the development and released versions of a package's website (when both of these exist).

For example, by default the pkgdown website goes to the documentation for the released version (https://pkgdown.r-lib.org); but the development version website can be accessed by adding `/dev/` to the URL (https://pkgdown.r-lib.org/dev/). However, this is a "hidden" feature, and it would be nice to make it obvious that a website for the development version is also available.

## Implementation

A simple implementation would be to add links to the homepage sidebar that use pkgdown's [selective HTML](https://pkgdown.r-lib.org/reference/build_site.html?q=select#selective-html) classes to dynamically show the appropriate link. For example, when you are on the release website you would see [View in-development version](https://pkgdown.r-lib.org/dev/) in the Links sidebar; and when you are on the development website you would see [View release version](https://pkgdown.r-lib.org) in the Links sidebar.

I believe the only changes needed to support this would be to update these lines to include the relevant *classed* links:

https://github.com/r-lib/pkgdown/blob/548a9493b72ff93d3ed8392d4ad30b77d8b15fa5/R/build-home-index.R#L161-L166

And to add an optional class argument to the internal `link_url()` function:

https://github.com/r-lib/pkgdown/blob/548a9493b72ff93d3ed8392d4ad30b77d8b15fa5/R/html-build.R#L5-L9

**Comment by hadley** [comment] 2024-04-11 22:01
Duplicate of #1373 

Unfortunately I think it's a little trickier than you outline because we don't always know if there's a dev or released site, and we don't want to generate broken links. I _think_ that implies we need to do something dynamically with js.

**Closed by hadley** 2024-04-11 22:01 UTC
