### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/pkgdown#676] opened 2018-05-23 02:55 UTC
Of course pkgdown works almost fine with GitHub:E, there seems some limitations related to the GitHub's URL. For example, I see:

* `#<issue id>` and `@<username>` in NEWS.md don't get converted to the links of the corresponding issues and users.

(I've sent a PR about this: #649)

**Comment by jayhesselberth** [comment] 2018-05-29 11:49
Can you provide an example of a URL from Github Enterprise (or better yet, a package and pkgdown site that lives on Github Enterprise).

**Comment by yutannihilation** [comment] 2018-05-29 11:54
Do you mean an *open* URL of GitHub Enterprise? I don't think there are any because they are intended to be used privately.

**Comment by jayhesselberth** [comment] 2018-05-29 12:08
I think `add_github_links` should be modified to use the `BugReports` field from DESCRIPTION.

https://github.com/r-lib/pkgdown/blob/421296fc500fe9066e75c8b54fe5a8e11862454b/R/github.R#L56-L57

I assume Github Enterprise issue numbers are just appended to the end of the URL (URl/issue_number). This is also the format that Bitbucket uses.

It's not clear to me what the equivalent would be for username linking (@username).

**Comment by yutannihilation** [comment] 2018-05-29 12:10
IIUC, the difference between GitHub and GitHub:E is just a base URL. Typically, the URL will be something like:

* `https://github.example.com/` (subdomain)
* `https://example.com/github/` (subpath)

And for each cases, the repo URL is:

* `https://github.example.com/<username>/<repo>/`
* `https://example.com/github/<username>/<repo>/`

The GitHub Pages URL is:

* `https://github.example.com/pages/<username>/<repo>/`
* `https://example.com/github/pages/<username>/<repo>/`

But, the document says the GitHub URL can be 

* `https://pages.github.example.com/pages/<username>/<repo>/`

References:

* https://help.github.com/enterprise/2.13/user/articles/user-organization-and-project-pages/
* https://help.github.com/enterprise/2.13/admin/guides/installation/enabling-subdomain-isolation/

**Comment by yutannihilation** [comment] 2018-05-29 12:12
Thanks for the idea! I agree with you to some extent, but I'm afraid `BugReports` is not always available for internally used packages.

**Comment by jayhesselberth** [comment] 2018-05-29 12:17
But wouldn't it encourage users to put it a BugReports field, even for internal packages? I'm not aware of situations where that field is disallowed.

**Comment by yutannihilation** [comment] 2018-05-29 12:27
OK, it sounds reasonable to me.

**Comment by hadley** [comment] 2020-03-11 20:03
Duplicate of new #1238

**Closed by hadley** 2020-03-11 20:03 UTC
Labels: feature, linking :paperclip:, wip
