### ISSUE TITLE
news output will be blank with certain subtitles

### ISSUE THREAD

**Issue by dracodoc** [r-lib/pkgdown#456] opened 2017-12-01 18:50 UTC
My news.md generate empty html without any content. I varied the content and found my usage of `v0.0.9` or `0.0.9` subtitle just caused empty output. I used `v0.0.9` because git tag need to start from letter.

```
# v0.0.9
all kinds of contents ....

# 0.0.9
 
```

Once I changed v0.0.9 into `version 0.0.9` it works.

**Comment by pat-s** [comment] 2017-12-02 09:23
The problem is a little bit bigger on my side. No changing of titles help, I get no output at all but also no error.

I found out that the problems start here (`data_news()`):

```r
sections <- xml2::read_html(html) %>% xml2::xml_find_all("./body/div")
titles <- sections %>% xml2::xml_find_first(".//h1|h2") %>% 
    xml2::xml_text(trim = TRUE)
```

`sections` and `titles` are both empty. So I assume that this is unrelated to `pkgdown` but is caused by `xml2`.

**Comment by wenjie2wang** [comment] 2017-12-02 13:35
I found the same problem as described by @pat-s (changing titles does not help)

However, IMHO, it is probably related to pandoc.  I am using pandoc v2.0.3 and the output format `markdown_github` is deprecated.  

I made one commit to solve the problem for my own usage: https://github.com/wenjie2wang/pkgdown/commit/ac7fb6ca0333882af5ae3406a48a3c99c07942f1

**Comment by pat-s** [comment] 2017-12-03 11:18
great, works for me as well!

can you make a PR @wenjie2wang so that this gets fixed? probably there needs to be an additional check for the pandoc version so that it will work for both v1 and v2

**Comment by adamhsparks** [comment] 2017-12-13 03:34
This is plaguing me as well. So far I've not been able to create a proper NEWS file in any of my `pkgdown` sites using the `r-lib` or @wenjie2wang's version.

This is with Pandoc 2.0.4 on macOS. Just an empty page is generated, e.g., https://adamhsparks.github.io/nasapower/news/index.html

**Comment by wenjie2wang** [comment] 2017-12-13 04:15
hey @adamhsparks , I just had a quick try on your `NEWS.md` file.  The patch https://github.com/wenjie2wang/pkgdown/commit/ac7fb6ca0333882af5ae3406a48a3c99c07942f1 seems to work.  

Notice that it is under the branch named `build-news-patch` (so we need install it with `devtools::install_github("wenjie2wang/pkgdown", ref = "build-news-patch")`).

**Comment by adamhsparks** [comment] 2017-12-13 04:28
Ah-ha! Thanks, @wenjie2wang. I missed the branch there. It does indeed work.

**Comment by sfirke** [comment] 2018-01-10 21:16
The branch from @wenjie2wang also fixed the problem of a blank `news/index.html` for me.  This was Pandoc v. 2.0.6 on Windows 10.

**Comment by hadley** [comment] 2018-02-20 20:49
This is now fixed in master thanks to @jennybc and @jimhester

**Closed by hadley** 2018-02-20 20:49 UTC
