### ISSUE TITLE
FR: A helper function for the reference index that will catch all not otherwise captured.

### ISSUE THREAD

**Issue by Moohan** [r-lib/pkgdown#2098] opened 2022-05-31 10:17 UTC
It would be great to have a helper function e.g. `everything()` which could be used as a catch-all for anything not otherwise captured by the reference index. At present, it throws a warning (or error in an action) if a function is missing from the reference. I would ideally have a  yml as follows.

```yml
url: ~
template:
  bootstrap: 5

reference:
  - title: Some functions
    desc: Functions which do `a`
  - contents:
    - starts_with("do_a")
 
  - title: Some other functions
    desc: Functions which do `b` 
  - contents:
    - starts_with("do_b")

  - title: Everything else
  - desc: Functions which don't fall into the other categories
  - contents:
    - everything()
```

**Comment by maelle** [comment] 2022-05-31 10:27
Duplicate of #1964

**Comment by maelle** [comment] 2022-05-31 10:27
Thanks @Moohan! It sure looks like a popular feature request!

**Closed by maelle** 2022-05-31 10:27 UTC
