### ISSUE TITLE
Code blocks with background color look very different in Bootstrap 5

### ISSUE THREAD

**Issue by davidchall** [r-lib/pkgdown#2086] opened 2022-05-04 15:52 UTC
I recognize that not everything will be supported with the Bootstrap 5 template, so please close this ticket if it's out of scope.

I use the `bg-info` and `bg-success` classes to differentiate input and output code blocks for my templating package [jinjar](https://github.com/davidchall/jinjar). Unfortunately, the background color is a bit too strong in the Bootstrap 5 template, making it difficult to read the text. I think perhaps the Bootstrap 3 template is applying an alpha to the background color?

With the bootstrap 3 template, it looks like this:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1804856/166719021-919bd531-873d-4817-8704-a2369e0c4121.png">

With the bootstrap 5 template, it looks like this:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1804856/166719196-f1c68624-4d46-40ad-b648-1f77d0948cee.png">

**Comment by hadley** [comment] 2022-05-31 21:14
This does seem to be by design in bs5 (https://getbootstrap.com/docs/5.0/utilities/background/), so I unfortunately I think it's out of scope for pkgdown.

**Closed by hadley** 2022-05-31 21:14 UTC
