### ISSUE TITLE
build_reference encoding issue

### ISSUE THREAD

**Issue by antuki** [r-lib/pkgdown#339] opened 2017-05-10 18:08 UTC
Hi, 

I'm having a problem of encoding with pkgdown. When I build my french website, the encoding is OK (UTF-8) for some of my pages but not the pages built with "build_reference" (functions documentations).

https://antuki.github.io/COGugaison/reference/changement_COG_varNum.html

In addition, i've noticed that there is no parameter called "encoding" in the build_reference function... And I have no problem when I install my package and I read the documentation on R  : the .Rd files are correctly encoded, the problem seems to be when there are transformed into .html with pkgdown. 

Do you have any idea of the origin of this problem ? 

Thank you very much.

**Comment by hadley** [comment] 2017-06-12 15:36
Have you tried the latest pkgdown? I can't reproduce this locally.

**Comment by antuki** [comment] 2017-06-18 15:41
Yes i just tried with the latest pkgdown. The french still doesn't want to appear correctly in function descriptions on the website...

**Comment by hadley** [comment] 2017-06-19 14:40
Can you please include the output of `devtools::session_info()`?

**Comment by cderv** [comment] 2017-06-20 06:12
I can reproduce it on my computer. Could be related to a french locale configuration of R. I previously encountered this issue so I will investigate. It could help find the cause.

**Comment by cderv** [comment] 2017-06-20 22:59
@hadley I think I found the source of the problem. 

In `docs/reference`, HTML files are not "UTF-8", but header is `<meta charset="utf-8">`. I tested it with 
`readr::guess_encoding("./docs/reference/changement_COG_typo.html")`  which is on my computer
```
# A tibble: 2 x 2
      encoding confidence
         <chr>      <dbl>
1 windows-1252       0.53
2 windows-1250       0.31
```
If I change the HTML header with `<meta charset="windows-1252">`, the file is looking ok on Firefox.

So it is an encoding issue. Pkgdown is expecting UTF-8 but do not have it. Why? 

I found that when template is rendered inside `build_reference`, it calls `write_if_different` which calls `cat`.  `cat` function with an argument file as character vector, like `file = path`,  opens by default a `file()` connection with `encoding = getOption("encoding")`. Issue is here, on windows and maybe on French windows
``` r
getOption("encoding")
#> [1] "native.enc"
```
and it is not *UTF-8*. 

So, `build_reference` generate UTF-8 html files. (`<meta charset="utf-8">`), however the filled template is written on html file using `cat` not as UTF-8. 

I tested to create UTF-8 file in my fork of pkgdown. First with, 
```r
withr::with_options(list(encoding = "UTF-8"),
                      cat(contents, file = path))
```  
but I choose not to add a dependency
```r
  file <- file(path, open = "w", encoding = "UTF-8")
  on.exit(close(file))
  cat(contents, file = file)
``` 
see cderv/pkgdown@3066967 in my repo this [branch](https://github.com/cderv/pkgdown/tree/encoding-reference)

With this version of pkgdown (cderv/pkgdown@3066967), when I run `readr::guess_encoding("./docs/reference/changement_COG_typo.html")` and it gives
```
# A tibble: 3 x 2
      encoding confidence
         <chr>      <dbl>
1        UTF-8       1.00
2 windows-1252       0.52
3 windows-1250       0.31`
```

I noticed `build_site` as an encoding argument but it is not pass through `build_reference`. So, I am not sure how you want to deal with encoding. I would go full UTF-8 but maybe not the best idea. 
It is why my branch is currently for test and not a PR. Tell me how to proceed if you think this is the correct way to deal with this issues and if you want one PR because we could change header template or change the way `cat` write the file.

**Comment by hadley** [comment] 2017-06-21 02:09
Thanks for the investigation!

I think we should always write UTF8. Do you want to do a PR? (Any encoding arguments in pkgdown should be about the input - we should always provide UTF8 output)

**Comment by cderv** [comment] 2017-06-21 05:43
yes I'll make a PR then.

**Comment by cderv** [comment] 2017-06-21 06:49
I opened the PR. 

However,  I noticed this issue is only for `build_reference` and not for home page but both are using `write_if_different` (as `build_home`, use `render_page` on `README.md`). The second one writes an UTF-8 file and i correct but not the first one with do not render reference pages correctly. 

Only difference is the way the input is parsed as parsing fonctions for `README.md` and Rd files with `tools::parsed_Rd` are not the same. 

It may be an irrelevant observation but I prefer to underline it as the fix I found could not be the right one.

**Comment by cderv** [comment] 2017-06-21 07:04
@antuki could you try to build site using pkgdown version from the PR branch and confirm that there are no side effects... I am not completely sure it is ok. thanks.

**Comment by antuki** [comment] 2017-06-24 10:27
Thank you for your investigations. 

I tried to build site with 
devtools::install_github("cderv/pkgdown")
and then with
devtools::install_github("hadley/pkgdown#362")
(I don't know if I did right about that ?)

and for both I now have an error  : 
 # Writing 'C:\Users\...\COGugaison\docs/authors.html' Error: pandoc document conversion failed with error 127

and then I tried again with 
devtools::install_github("hadley/pkgdown")
It runs but I still have the same encoding issues than before

About the devtools session : 

> devtools::session_info()
Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  French_France.1252          
 tz       Europe/Paris                
 date     2017-06-24                  

Packages -----------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.3.2   2016-10-31 local         
 datasets  * 3.3.2   2016-10-31 local         
 devtools  * 1.13.2  2017-06-02 CRAN (R 3.3.3)
 digest      0.6.12  2017-01-27 CRAN (R 3.3.2)
 graphics  * 3.3.2   2016-10-31 local         
 grDevices * 3.3.2   2016-10-31 local         
 highlight   0.4.7.1 2017-03-21 CRAN (R 3.3.3)
 memoise     1.1.0   2017-04-21 CRAN (R 3.3.3)
 methods   * 3.3.2   2016-10-31 local         
 stats     * 3.3.2   2016-10-31 local         
 tools       3.3.2   2016-10-31 local         
 utils     * 3.3.2   2016-10-31 local         
 withr       1.0.2   2016-06-20 CRAN (R 3.3.2)

**Comment by cderv** [comment] 2017-06-25 09:17
I believe it is nothing to do with changes I made. It seems that my branch start at a old commit where your site does not built. As it builds with last dev version of pkgdown, there is no more issue. I just need to find time to finish the PR (next week I think). 

If you want, You could try again from PR branch but build only reference pages with `build_reference` function to skip the part with pandoc conversion problem. They should then appear in your site without encoding issue.

**Comment by antuki** [comment] 2017-06-25 10:53
Merci Christophe. 

I tried build_reference as you said. 
Now the index is correct : https://antuki.github.io/COGugaison/reference/index.html 
But the encoding issues still remain in each pages such as : https://antuki.github.io/COGugaison/reference/changement_COG_typo.html 

And when I look on the documentation of the package, directly on R, I have the opposite problem
?changement_COG_typo => No encoding issue
But when I click on "Index" => encoding issues !
For these two examples, there is no link with pkgdown but I didn't managed to correct them neither... 

Thanks for your help.

**Comment by cderv** [comment] 2017-06-27 20:54
Just for you to know `build_reference` only build non existing reference page. You need to delete old ones if you want encoding issue to be resolved on each pages.

**Comment by antuki** [comment] 2017-07-08 18:18
Thanks it worked ! 

I still have a problem with the index of the documentation directly on R (if you have the solution...) but no more encoding issue with pkgdown ! 

When will it be integrated to the real pkgdown ? 

By the way, about french, is it possible to change easily the names of the differents parts of the pkgdown websites (translate references, articles... into french) ? 

Thank you !

**Comment by cderv** [comment] 2017-11-18 14:53
Yes PR has not beean merged yet. Maybe I can rebase to include in my change in last pkgdown version. It should not break thinks... will try and test when I find some spare time.
You confirm my branch still working for you ? 
Know that, in the meantime, it is possible to post-encode the files generated by `pkgdown`. An adding step but could be useful if you need to publish it.

**Comment by antuki** [comment] 2017-11-18 18:31
Yes "hadley/pkgdown#362" is still working. 
I build_reference with this branch and then I build the rest with hadley's master branch. 
And then I have to modify manually one thing in the reference index : the navbar which contains "Articles" in your version but not "Get started" and the home icon. 
What do you mean when you say "post-encode" ? 
Thanks Christophe.

**Closed** 2018-02-20 14:14 UTC
Labels: bug, rd-translation

**Comment by antuki** [comment] 2018-02-23 01:17
Thank you @hadley ! Sorry but i still have encoding issues. 
Now build_reference is generating correct encoding, build_article is also still working. 
**But unfortunately the files generated with build_home and build_news are wrong now (wrong encoding).** 
How could you explain that @cderv ? 
Thank you !

**Comment by cderv** [comment] 2018-02-24 11:50
I reproduced the issue on my French computer launching `build_site` on your repo. 

The issue is in another place now. So I'll open a new issue to discuss it.
