### ISSUE TITLE
pkgdown does not respect \dontshow

### ISSUE THREAD

**Issue by cboettig** [r-lib/pkgdown#1540] opened 2021-03-02 18:39 UTC
`\dontshow` is standard syntax to suppress parts of the examples that should not be displayed in the documentation, but `pkgdown` ignores the tag and displays these anyway (understandable since pkgdown isn't running `LaTeX`, but you see my point).

I know `\dontshow` isn't commonly used, historically it would be used to hide test conditions where "examples" doubled as "unit-tests" (though there is a certain Knuth-ian literate programming flavor to having your tests sit next to your source-code).  I also find `\dontshow` preferable for setting things like environmental variables that are only relevant to meet CRAN requirements (i.e. not writing to disk outside temp storage), since it confuses some users to show examples that show commands writing to a temporary location on operations that intend to persist between sessions.  Anyway, a minor issue but I think it is worth noting.

**Comment by maelle** [comment] 2021-03-08 09:49
Related https://pkgdown.r-lib.org/reference/test-dont.html and https://github.com/r-lib/pkgdown/blob/9c95f00d2505ddd83c4722e019202370715d3a3d/R/test.R#L123

**Comment by maelle** [comment] 2021-05-25 11:44
I wonder whether downlit could recognize the dontshow comments and put them in a `.d-none` div. :thinking: (maybe even a div class whose display could be controlled by a "bslib" variable).

Probably quite niche. :wink:

**Comment by maelle** [comment] 2021-05-25 11:55
(or pkgdown itself based on the HTML produced by downlit)

**Comment by krlmlr** [comment] 2021-07-24 16:31
I wanted to work around https://github.com/r-lib/downlit/issues/101, because `\dontshow{}` isn't respected yet I ended up with https://github.com/r-lib/pillar/pull/340.

**Comment by hadley** [comment] 2021-09-21 18:36
I think in principle this is a good idea, but I know from past experience there's a lot of variation in the way that people use `\dontshow{}` (meaning this is likely to be more work than expected) and IMO `\dontshow{}` tends to make overly magical examples (which means that I don't want to spend my time on this issue). So I'm closing this issue to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Closed by hadley** 2021-09-21 18:36 UTC

**Comment by hadley** [comment] 2021-09-21 21:20
Yes, `@examplesIf` is likely to get special handling.
