### ISSUE TITLE
\cr tag from .Rd files is ignored

### ISSUE THREAD

**Issue by GegznaV** [r-lib/pkgdown#387] opened 2017-08-01 17:26 UTC
`\cr` tag from `.Rd` files is ignored while converting to HTML as in reference pages on `pkgdown` site no new lines are created.

**Comment by hadley** [comment] 2018-02-20 17:24
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2018-03-14 16:37
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Comment by GegznaV** [comment] 2018-03-20 09:59
I created a new package with RStudio and called the package "aaa.example"

The R script that creates and describes a function is below. Argument `text` has several new lines (tag `\cr`) in its description:

```r
#' The 'hello' function
#'
#'
#' @param text (character) \cr Text that is ignored. \cr New line.
#'
#' @export
#'
hello <- function(text) {
  print("Hello, world!")
}
```

I built the package and a `pkgdown` site.

Description of `text` in the documentation in the RStudio "Help" window (new lines are **present**):

![image](https://user-images.githubusercontent.com/12725868/37645589-fc004118-2c2f-11e8-88c8-7b5f554c8f2d.png)

The same description in the `pkgdown` site (new lines are **missing**):

![image](https://user-images.githubusercontent.com/12725868/37645661-2bda6fc6-2c30-11e8-9ff5-2d555db83998.png)

**Comment by batpigandme** [comment] 2018-03-20 10:22
Have you tried this with the `cr/` at the end of the line, as in the example here:
https://stackoverflow.com/a/24165701

**Comment by GegznaV** [comment] 2018-03-20 11:46
Do you mean like this:

```r
#' @param text (character) \cr
#'  Text that is ignored. \cr
#'  New line. 
```

No effect.

**Comment by hadley** [comment] 2018-03-20 14:48
Minimal reprex: `rd2html("a \\cr b")`

**Closed** 2018-03-20 14:50 UTC
Labels: bug, rd-translation
