### ISSUE TITLE
Code chunks in vignette truncated when rendered with build_site()

### ISSUE THREAD

**Issue by PascalIrz** [r-lib/pkgdown#1292] opened 2020-04-07 07:52 UTC
Hello,

I am writing my first R package and would like it on Github Pages.

Problem is that the vignette '.Rmd" file, when rendered by build_site(), omits some parts of some code chunks. I noted that chunks with "%" characters are more prone to this. Conversly, the same vignette is rendered fine when rendered using the "knit" button in RStudio. 

*No error / warning is displayed : 
> pkgdown::build_site()
-- Installing package into temporary library -----------------------------------
|= Building pkgdown site ===============================================
Reading from: 'D:/Pascal/boulot/rty2_github'
Writing to:   'D:/Pascal/boulot/rty2_github/docs'
|- Initialising site -------------------------------------------------------------------------------------------
|- Building home -------------------------------------------------------------------------------------------
-- Building function reference -----------------------------------------------------------------------------
-- Building articles -----------------------------------------------------------------------------------------
Reading 'vignettes/documentation.Rmd'
|= DONE =========================================================
-- Previewing site -------------------------------------------------------------*

To produce reproducible examples, I created an example R package: https://pascalirz.github.io/rty2/

Is this a real issue or is there something I missed ?

Thanks in advance.

**Comment by jayhesselberth** [comment] 2020-04-07 11:03
Duplicate of #1282. This will be fixed in a patch release soon.

**Closed by jayhesselberth** 2020-04-07 11:03 UTC

**Comment by PascalIrz** [comment] 2020-04-07 18:10
Thanks for your quick answer, however, I think what I described is different from #1282 

In my issue, the dysfunctional code chunk is evaluated; its output is Ok but the chunk itseld (echo = T) is only partially displayed in the html vignette produced by build_site(). Although the very same .Rmd file displays well if knitted directly in with knit().

**Comment by hadley** [comment] 2020-04-07 18:18
@PascalIrz that sounds exactly like the problem in #1282

**Comment by PascalIrz** [comment] 2020-04-07 20:22
Ok, then. Thanks a lot.
