### ISSUE TITLE
Vigniette/Get Started - broken link has "//" in it and gets worse with every click

### ISSUE THREAD

**Issue by SchmidtPaul** [r-lib/pkgdown#1520] opened 2021-02-23 09:33 UTC
Sorry, I feel like I am overlooking something, but I couldn't find a solution anywhere.

I have this github page https://schmidtpaul.github.io/CitaviR//index.html which works fine for the main page and the [reference page](https://schmidtpaul.github.io/CitaviR//reference/index.html) although `//` irritates me. However, when navigating to the [Get started page](https://schmidtpaul.github.io/CitaviR//articles/CitaviR.html), we get a *Page not found (404)*. Furthermore, when trying to navigate to *Get started* again, the URL adds another `/articles` like so: https://schmidtpaul.github.io/CitaviR//articles/articles/CitaviR.html and you can repeat this as many times as you want.

Note that in `pkgdown::preview_site()` everything works fine.

Here are links to

- [the repository](https://github.com/SchmidtPaul/CitaviR)
- [the master/_pkgdown.yml](https://github.com/SchmidtPaul/CitaviR/blob/master/_pkgdown.yml)
- [the master/docs/pkgdown.yml](https://github.com/SchmidtPaul/CitaviR/blob/master/docs/pkgdown.yml)
- [the master/.Rbuildignore](https://github.com/SchmidtPaul/CitaviR/blob/master/.Rbuildignore)

How do I fix this?

**Comment by maelle** [comment] 2021-02-23 12:38
Duplicate of 1356 (I think?)

**Comment by hadley** [comment] 2021-02-23 12:54
That makes it worse, but the root problem (trailing `/` in url) is fixed in https://github.com/SchmidtPaul/CitaviR/pull/9.

**Closed by hadley** 2021-02-23 12:54 UTC
