### ISSUE TITLE
"twitter-bootstrap" breaks menu bar dropdown of custom themes

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#1176] opened 2019-11-07 15:51 UTC
https://github.com/r-lib/pkgdown/blob/dfae44ecfcc5b0ac51f9489993ddd79ad6c707c3/inst/templates/head.html#L22

Here, `twitter-bootstrap` is loaded directly. If one sets a custom bootstrap theme in `_pkgdown.yml`, the menu bar dropdown breaks. In particular, no menu pops up when clicking on navbar menus and the following error occurs:

![2019-11-07-164819_screenshot](https://user-images.githubusercontent.com/8430564/68404424-d0def080-017e-11ea-8bb8-ff39b1fe942e.png)

```yml
template:
  package: mlr3pkgdowntemplate
  params:
    bootswatch: journal
```

Everything works when reverting to the previous state without `twitter-bootstrap`:

```js
{{^bootswatch}}<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">{{/bootswatch}}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```

**Comment by Bisaloo** [comment] 2019-12-06 10:46
```bash
curl https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css | md5sum
```

> ec3bb52a00e176a7181d454dffaea219

 ```bash
curl https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css | md5sum
```

> ec3bb52a00e176a7181d454dffaea219

Even though the two CDNs use different names for the file, the file contents are exactly the same. So it should not cause any error... Could you provide a link with an example so I can look into it please?

**Comment by pat-s** [comment] 2019-12-06 14:00
> Even though the two CDNs use different names for the file, the file contents are exactly the same. So it should not cause any error.

Interesting.

[Here](https://github.com/mlr-org/mlr3pkgdowntemplate/blob/86b29e08490594007239e0ab3ac86586f02bfbbd/inst/pkgdown/templates/head.html#L22) is the `head.html` of our custom pkgdown template.

If you apply the changes outlined above (important is to use the "journal" theme), you should come across this issue.
This should be reproducible by providing a local assets path and then building the site locally.

**Comment by Bisaloo** [comment] 2019-12-06 17:04
I tried adding 

```
template:
  package: mlr3pkgdowntemplate
  params:
    bootswatch: journal
```

to one of my package and everything seems to work fine. Am I missing something?

Is https://mlr.mlr-org.com/ currently broken for you for example?

**Comment by pat-s** [comment] 2019-12-07 09:58
Did you exchange the lines as mentioned in the initial post? I.e. use the current approach via cdnjs instead of maxcdn?

mlr.mlr-org.com is fine as I reverted back using maxcdn.

**Comment by Bisaloo** [comment] 2019-12-07 11:08
Thanks for the info. I can reproduce with 

```r
remotes::install_github("mlr-org/mlr3pkgdowntemplate@5b68761438863d972cacfb9beea63231bfa4095d")
```

but not [with my fork where I put cdnjs back](https://github.com/mlr-org/mlr3pkgdowntemplate/compare/master...Bisaloo:patch-1?expand=1):

```r
remotes::install_github("bisaloo/mlr3pkgdowntemplate@patch-1")
```

This, combined with the fact that your error messages posted in the OP don't mention bootstrap at all, makes me this your issue is not due to this change.

I couldn't find the exact source of the problem though :thinking:

**Comment by Bisaloo** [comment] 2019-12-07 11:28
If you use a custom `bootswatch` theme, that line:

https://github.com/r-lib/pkgdown/blob/dfae44ecfcc5b0ac51f9489993ddd79ad6c707c3/inst/templates/head.html#L22

is not even included in your final source code.

**Comment by pat-s** [comment] 2019-12-07 11:45
> This, combined with the fact that your error messages posted in the OP don't mention bootstrap at all, makes me this your issue is not due to this change.

This could very well be. Then its most likely combination of changes which in the end is triggered by the bootswatch change. 

Even though this is strange because both template hashes are identical in the end as you've shown.

I do not know if its worth digging further as I am happy with the current workaround and maybe this problem solves itself at some point? Also it looks like it is triggered by a custom change on our side then and does not apply to pkgdown vanilla.

Thanks for looking into it!

**Comment by hadley** [comment] 2020-03-10 21:57
Closing since you seem to have a work around.

**Closed by hadley** 2020-03-10 21:57 UTC
