### ISSUE TITLE
Unnecessary Error message for missing topic using `- title: internal`

### ISSUE THREAD

**Issue by elong0527** [r-lib/pkgdown#1951] opened 2021-12-03 22:50 UTC
In `_pkgdown.yml`, we will get error message if we set `- title: internal` for the `reference` part. 

The issue is documented in the github action log. 

Error: https://github.com/Merck/r2rtf/actions/runs/1537336939

Passed: https://github.com/Merck/r2rtf/actions/runs/1537329545

Difference: https://github.com/Merck/r2rtf/commit/e598fa206240f4a6b1ccb4be602387c9ed6b931b

**Comment by hadley** [comment] 2021-12-03 22:59
Could you please include the error message inline?

**Comment by elong0527** [comment] 2021-12-03 23:09
Sure, below is the error message. 

When I build local using `pkgdown::build_reference_index()`, I only receive warning message. 

```
== Building pkgdown site =======================================================
Reading from: '/home/runner/work/r2rtf/r2rtf'
Writing to:   '/tmp/RtmpltBiJU/file325a5e5a1a3c'
-- Initialising site -----------------------------------------------------------
Copying '../../_temp/Library/pkgdown/BS5/assets/link.svg' to 'link.svg'
Copying '../../_temp/Library/pkgdown/BS5/assets/pkgdown.js' to 'pkgdown.js'
Copying 'pkgdown/extra.css' to 'extra.css'
-- Building home ---------------------------------------------------------------
Writing 'authors.html'
Writing 'LICENSE-text.html'
Writing '404.html'
-- Building function reference -------------------------------------------------
Error: Error: Topics missing from index: as_rtf_colheader
* Topics missing from index: as_rtf_color
* Topics missing from index: as_rtf_end
* Topics missing from index: as_rtf_font
* Topics missing from index: as_rtf_footnote
* Topics missing from index: as_rtf_init
* Topics missing from index: as_rtf_margin
* Topics missing from index: as_rtf_new_page
* Topics missing from index: as_rtf_page
* Topics missing from index: as_rtf_pageby
* Topics missing from index: as_rtf_paragraph
* Topics missing from index: as_rtf_source
* Topics missing from index: as_rtf_subline
* Topics missing from index: as_rtf_table
* Topics missing from index: as_rtf_title
* Topics missing from index: border_type
* Topics missing from index: cell_size
* Topics missing from index: check_args
* Topics missing from index: color_table
* Topics missing from index: convert
* Topics missing from index: font_format
* Topics missing from index: font_type
* Topics missing from index: footnote_source_space
* Topics missing from index: inch_to_twip
* Topics missing from index: justification
* Topics missing from index: match_arg
* Topics missing from index: nrow_paragraph
* Topics missing from index: nrow_table
* Topics missing from index: obj_rtf_border
* Topics missing from index: obj_rtf_text
* Topics missing from index: rtf_by_subline
* Topics missing from index: rtf_convert_format
* Topics missing from index: rtf_encode_figure
* Topics missing from index: rtf_encode_list
* Topics missing from index: rtf_encode_table
* Topics missing from index: rtf_group_by_enhance
* Topics missing from index: rtf_nline_matrix
* Topics missing from index: rtf_nline_vector
* Topics missing from index: rtf_nrow
* Topics missing from index: rtf_pageby
* Topics missing from index: rtf_paragraph
* Topics missing from index: rtf_strwidth
* Topics missing from index: rtf_subset
* Topics missing from index: rtf_table_content
* Topics missing from index: rtf_text
* Topics missing from index: set_margin
* Topics missing from index: spacing
* Topics missing from index: update_border_first
* Topics missing from index: update_border_last
* Topics missing from index: utf8Tortf
* Topics missing from index: vertical_justification
* Topics missing from index: write_rtf_para
Backtrace:
     █
  1. └─pkgdown::deploy_to_branch(new_process = FALSE)
  2.   └─pkgdown::build_site_github_pages(...)
  3.     └─pkgdown::build_site(...)
  4.       └─pkgdown:::build_site_local(...)
  5.         └─pkgdown::build_reference(...)
  6.           └─pkgdown::build_reference_index(pkg)
  7.             ├─pkgdown::render_page(...)
  8.             │ └─pkgdown:::render_page_html(pkg, name = name, data = data, depth = depth)
  9.             │   └─utils::modifyList(data_template(pkg, depth = depth), data)
 10.             │     └─base::stopifnot(is.list(x), is.list(val))
 11.             └─pkgdown:::data_reference_index(pkg)
 12.               └─pkgdown:::check_missing_topics(rows, pkg)
11 Removing worktree 11111111111111111111111111111111111111111111111111111111111
Running git worktree remove /tmp/RtmpltBiJU/file325a5e5a1a3c
Execution halted
Error: Process completed with exit code 1.
```

**Comment by hadley** [comment] 2022-01-06 01:35
Duplicate of #1958

**Closed by hadley** 2022-01-06 01:35 UTC
