### ISSUE TITLE
Escaped underscores in math mode not displayed correctly

### ISSUE THREAD

**Issue by fweber144** [r-lib/pkgdown#2277] opened 2023-02-11 15:11 UTC
pkgdown does not seem to display escaped underscores in math equations correctly: In [this "Details" section](https://mc-stan.org/projpred/reference/suggest_size.html#details-1), it is displayed as `\_` (at `nterms\_max`), but it should be displayed as `_`. The HTML help within RStudio and also the [PDF](https://cran.r-project.org/web/packages/projpred/projpred.pdf) display underscores correctly.

According to the suggestions [here](https://tex.stackexchange.com/questions/48632/underscores-in-words-text), I also tried ``\char`_`` and `\detokenize{}`, but neither helped.

**Comment by maelle** [comment] 2023-02-21 16:35
I tried `\mathrm{nterms\_max}` from https://github.com/mathjax/MathJax/issues/1770 which seems to work

![image](https://user-images.githubusercontent.com/8360597/220404877-60671ba6-6969-4356-976e-0f7fa14b9c45.png)

However even if it works for you it'd still be a quick fix and it'd be nice to understand why it is so. :sweat_smile:

**Comment by maelle** [comment] 2023-02-21 16:36
(that screenshot is from a "test" pkgdown website)

**Comment by fweber144** [comment] 2023-02-21 19:47
Thanks! I'm not a TeX expert, but isn't `\mathrm{}` a different font family than typewriter font (in the screenshot, `nterms_max` also doesn't seem to be in typewriter font)?

**Comment by fweber144** [comment] 2023-02-21 19:49
And sorry—I should have mentioned directly in the first comment that I'd like to have `nterms_max` in typewriter font.

**Comment by maelle** [comment] 2023-02-22 08:18
The reason why I thought it might help to add the Pandoc parsing of LaTeX earlier is that it's what happens for articles, and maybe soon for the README #2263

I'll leave this aside now, sorry to not be of more help. :sweat_smile:

**Comment by fweber144** [comment] 2023-02-23 12:28
No problem, thanks for investigating this! I think for now, I'll leave it as-is.

**Comment by hadley** [comment] 2024-04-19 19:47
Given that https://github.com/mathjax/MathJax/issues/1770 suggests it's a pkgdown limitation, there's a workaround (via `\mathm{}`, albeit imperfect), and it doesn't seem to affect too many people, I think it's unlikely this will ever rise to the top of our to do list. So I'm going to close it, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Closed by hadley** 2024-04-19 19:47 UTC
Labels: bug, reference :books:
