### ISSUE TITLE
404 page fails to fetch pkgdown.css in some cases

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1121] opened 2019-08-28 14:50 UTC
The 404 page looks fine when the non-existing page is directly in the website root:

http://rafaelmaia.net/pavo/thispagedoesnotexist

![Screenshot from 2019-08-28 16-50-00](https://user-images.githubusercontent.com/10783929/63866686-e207c600-c9b3-11e9-8388-f0ca9408393d.png)

But it fails to fetch `pkgdown.css` for non-existing pages in subfolder:

http://rafaelmaia.net/pavo/articles/thispagedoesnotexist

![Screenshot from 2019-08-28 16-50-25](https://user-images.githubusercontent.com/10783929/63866697-e8963d80-c9b3-11e9-9488-388aef4622a2.png)

because the desired CSS file is `../pkgdown.css` and not `pkgdown.css` in this case.

`pkgdown.js`, `docsearch.css` and `docsearch.js` have the same issue.

**Comment by hadley** [comment] 2019-08-30 12:12
Duplicate of #1129 (closing this one because that issue has more details)

**Closed by hadley** 2019-08-30 12:12 UTC
Labels: bug, help wanted :heart:, home :house:
