### ISSUE TITLE
ignored articles end up in docs/pkgdown.yml

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#1340] opened 2020-06-02 16:29 UTC
as per [the docs](https://pkgdown.r-lib.org/reference/build_articles.html):

> Files that start with _ (e.g., _index.Rmd) are ignored.

However, `touch vignettes/_foo.Rmd` and running `pkgdown::render_site()` *does* yield this `docs/pkgdown.yml`:

```yaml
pandoc: 2.9.2.1
pkgdown: 1.5.1
pkgdown_sha: ~
articles:
  _foo: _foo.html
  about: about.html
  interactive: interactive.html
last_built: 2020-06-02T16:00Z
```

I'm not sure who/what is using the *rendered* `docs/pkgdown.yml`, but it seems odd and potentially buggy to include `_foo.html` here, which is a path that rightfully does *not* exist and is *not* actually an article.

(I'm also having trouble getting a pkgdown page indexed by docsearch, and am currently guessing that this might have something to do with the problem, but that's entirely speculative as per https://github.com/subugoe/hoad/issues/82).

**Comment by jayhesselberth** [comment] 2020-06-02 17:45
We should not include ignored files to the site yaml, as you said, it's a path that doesn't exist.

Docsearch doesn't look at the pkgdown config file, it only uses the sitemap.xml to know which files to index. Your site [doesn't include the ignored file](https://subugoe.github.io/hoad/sitemap.xml).

**Comment by maelle** [comment] 2021-05-18 09:17
* I cannot reproduce this anymore, I suspect it might have been fixed by https://github.com/r-lib/pkgdown/commit/2c210e86c82ea19f74c122c7329dad11a647e956 I think this issue can be closed?
* Regarding search, in the dev version if you use Bootstrap 4 the search is local, with a search index built by pkgdown itself.

**Closed** 2021-05-18 10:56 UTC
Labels: articles :writing_hand:, bug
