### ISSUE TITLE
how to handle vignettes with child documents?

### ISSUE THREAD

**Issue by ThierryO** [r-lib/pkgdown#463] opened 2017-12-09 13:59 UTC
I have a package [`INBOtheme`](https://github.com/inbo/inbotheme) which is a collection of `ggplot2` themes. The vignette applies as the themes to the same set of plots. Therefore I've placed that section into a [child document](https://github.com/inbo/INBOtheme/blob/master/vignettes/themes_test_figures.Rmd) which is called repeatedly into the [vignette](https://github.com/inbo/INBOtheme/blob/master/vignettes/themes.Rmd). `pkgdown` tries to render the child document as a standalone document which obviously fails.

Who can I tell `pkgdown` to ignore the child document?

**Comment by hadley** [comment] 2018-02-20 23:24
Duplicate of #457

**Closed by hadley** 2018-02-20 23:24 UTC
Labels: articles, feature
