### ISSUE TITLE
Error: callr subprocess failed: Failed to parse Rd i Graphics API version mismatch

### ISSUE THREAD

**Issue by nandp1** [r-lib/pkgdown#1761] opened 2021-08-29 05:10 UTC
I am trying to build website for my package. But when i use 
`pkgdown::build_site()` I get the following error, 

```
Reading 'man/bhav.Rd'
Error : Failed to parse Rd in bhav.Rd
i Graphics API version mismatch
Error: callr subprocess failed: Failed to parse Rd in bhav.Rd
i Graphics API version mismatch
Type .Last.error.trace to see where the error occurred
```
But I can view website through `pkgdown::build_home()`
What is causing this issue? 

My session info 
```

R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   knitr_1.33        rematch2_2.1.2    magrittr_2.0.1    usethis_2.0.1     R6_2.5.1          rlang_0.4.11      fastmap_1.1.0    
 [9] fansi_0.5.0       tools_4.1.0       xfun_0.25         utf8_1.2.2        cli_3.0.1         withr_2.4.2       htmltools_0.5.1.1 ellipsis_0.3.2   
[17] digest_0.6.27     yaml_2.2.1        rprojroot_2.0.2   tibble_3.1.3      lifecycle_1.0.0   pkgdown_1.6.1     crayon_1.4.1      processx_3.5.2   
[25] callr_3.7.0       purrr_0.3.4       ps_1.6.0          vctrs_0.3.8       fs_1.5.0          evaluate_0.14     memoise_2.0.0     glue_1.4.2       
[33] cachem_1.0.6      rmarkdown_2.10    compiler_4.1.0    pillar_1.6.2      desc_1.3.0        pkgconfig_2.0.3  
```

**Comment by hadley** [comment] 2021-09-21 17:53
Can you please create a minimal reprex package, by progressively deleting the contents of the package until you figure out what's causing the problem?

**Comment by hadley** [comment] 2021-09-21 17:56
Probably duplicate of #1751

**Closed** 2021-09-27 18:42 UTC
Labels: reprex
