### ISSUE TITLE
build_site(install = FALSE) errors on building vignettes in 1.5.0

### ISSUE THREAD

**Issue by nealrichardson** [r-lib/pkgdown#1283] opened 2020-04-02 00:01 UTC
On a nightly GitHub Actions job, I build the pkgdown site for `arrow` by first installing the package and then running `build_site(install = FALSE)` from the local git checkout. It was faster/more efficient to install this way and take advantage of binary packages, as compilation can be slow for `arrow`. 

Using pkgdown 1.5.0, site building fails [here](https://github.com/ursa-labs/arrow-r-nightly/runs/550202723?check_suite_focus=true#step:9:170):

```
...
Writing 'reference/write_arrow.html'
Reading 'man/write_feather.Rd'
Writing 'reference/write_feather.html'
Reading 'man/write_parquet.Rd'
Writing 'reference/write_parquet.html'
── Building articles ───────────────────────────────────────────────────────────
Error : '/tmp/RtmpdXSKbx/file366362fa1820' must be non-empty
In addition: Warning message:
Topics missing from index: 
* FileFormat
* FileInfo 

Error: <callr_status_error: callr subprocess failed: '/tmp/RtmpdXSKbx/file366362fa1820' must be non-empty>
-->
<callr_remote_error: '/tmp/RtmpdXSKbx/file366362fa1820' must be non-empty>
 in process 13923 

 Stack trace:
 Process 13898:
 1. pkgdown::build_site(install = FALSE)
 2. pkgdown:::build_site_external(pkg = pkg, examples = examples,  ...
 3. callr::r(function(..., crayon_enabled, crayon_colors, pkgdown_internet) { ...
 4. callr:::get_result(output = out, options)
 5. throw(newerr, parent = remerr[[2]])

 x callr subprocess failed: '/tmp/RtmpdXSKbx/file366362fa1820' must be non-empty 

 Process 13923:
 17. (function (..., crayon_enabled, crayon_colors, pkgdown_internet)  ...
 18. pkgdown::build_site(...)
 19. pkgdown:::build_site_local(pkg = pkg, examples = examples, run_dont_run = r ...
 20. pkgdown:::build_articles(pkg, lazy = lazy, override = override,  ...
 21. pkgdown:::build_articles_index(pkg)
 22. pkgdown:::render_page(pkg, "article-index", data = data_articles_index(pkg) ...
 23. utils::modifyList(data, data_template(pkg, depth = depth))
 24. base:::stopifnot(is.list(x), is.list(val))
 25. pkgdown:::data_articles_index(pkg)
 26. magrittr:::`%>%`(meta %>% purrr::map(data_articles_index_section,  ...
 27. base:::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
 28. base:::eval(quote(`_fseq`(`_lhs`)), env, env)
 29. base:::eval(quote(`_fseq`(`_lhs`)), env, env)
 30. pkgdown:::`_fseq`(`_lhs`)
 31. magrittr:::freduce(value, `_function_list`)
 32. function_list[[i]](value)
 33. purrr::map(., data_articles_index_section, pkg = pkg)
 34. pkgdown:::.f(.x[[i]], ...)
 35. tibble::tibble(name = section_vignettes$name, path = path_rel(section_vigne ...
 36. tibble:::lst_quos(xs, transform = expand_lst)
 37. rlang:::eval_tidy(xs[[i]], unique_output)
 38. base:::lapply(section_vignettes$description, markdown_text)
 39. pkgdown:::FUN(X[[i]], ...)
 40. pkgdown:::markdown(tmp, ...)
 41. base:::stop(src_path(path), " must be non-empty", call. = FALSE)
 42. base:::.handleSimpleError(function (e)  ...
 43. h(simpleError(msg, call))

 x '/tmp/RtmpdXSKbx/file366362fa1820' must be non-empty 

Execution halted
```

If I downgrade to 1.4.1, it [succeeds](https://github.com/ursa-labs/arrow-r-nightly/runs/553475818?check_suite_focus=true).

It may be relevant that the version of the package that was installed was built with `--no-build-vignettes`, so I wonder if 1.5.0 is looking for vignettes in the installed package (which do not exist) and not in the local directory (where they do exist).

Maybe 1.5.0 is now working as it was supposed to, and the fact that it worked before was just another instance of [Hyrum's Law](https://www.hyrumslaw.com/), so I won't be offended if this is "wontfix".

**Comment by nealrichardson** [comment] 2020-04-02 00:28
I may have misdiagnosed this: I reworked the GHA workflow not to use `install = FALSE` and it still [failed the same way](https://github.com/ursa-labs/arrow-r-nightly/runs/553580189?check_suite_focus=true).

**Comment by hadley** [comment] 2020-04-02 12:15
Slightly simpler reprex 😝 

``` r
pkgdown:::markdown_text("")
#> Error: '/tmp/Rtmp6yTlF9/fileb09517787e6f' must be non-empty
```

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2020-04-02 12:17
(However, the root cause is likely to be higher up — I suspect `package_vignettes()` might be returning the wrong thing in your set up)

**Comment by nealrichardson** [comment] 2020-04-02 21:56
Ok, LMK if you have ideas for how I could debug the setup or provide more information.

**Comment by hadley** [comment] 2020-04-03 20:56
Here's the problem: https://github.com/apache/arrow/blob/master/r/vignettes/dataset.Rmd#L3

So it's fixed in dev, and I'll push a release to CRAN next week

**Closed by hadley** 2020-04-03 20:56 UTC
