### ISSUE TITLE
incorrect parsing of library

### ISSUE THREAD

**Issue by dkarletsos** [r-lib/pkgdown#2431] opened 2024-03-25 16:20 UTC
Hi,

There seems to be an issue with how the parsing of the package is being done.

I know it used to work in version 1.5.1 . 

```
Rscript -e "pkg <- '.'; pkgdown::init_site(pkg); pkgdown::build_home(pkg); pkgdown::build_reference(pkg, examples=FALSE); pkgdown::build_news(pkg); withr::with_temp_libpaths(action = 'prefix', { devtools::install(pkg, upgrade = 'never', reload = FALSE, quiet = FALSE); pkgdown::build_articles(pkg); })"
Using environment default (R version: 4.1.3, platform: aarch64-apple-darwin20)
Warning: Failed to parse usage:

S3method(`$`, ``safeenv::safeenv``)(obj, name)

Warning: Failed to parse usage:

S3method(`$`, ``safeenv::safeenv``)(obj, name) <- value

Warning: Failed to parse usage:

S3method(`[[`, ``safeenv::safeenv``)(obj, name)

Warning: Failed to parse usage:

S3method(`[[`, ``safeenv::safeenv``)(obj, name) <- value
```

**Comment by maelle** [comment] 2024-03-26 08:35
Is your package public?

Any reason why you don't use `pkgdown::build_site()` directly instead of calling the various steps?

**Comment by maelle** [comment] 2024-03-26 11:16
Ah! Then it is likely a duplicate of #2186

**Comment by maelle** [comment] 2024-03-26 12:04
Duplicate of #2186

**Closed by maelle** 2024-03-26 12:04 UTC
