### ISSUE TITLE
Support GitLab for page source printing

### ISSUE THREAD

**Issue by msberends** [r-lib/pkgdown#1045] opened 2019-05-28 08:02 UTC
When the `URL` field in the DESCRIPTION file contains github.com, the page source is printed on all reference pages:

```yaml
URL: https://msberends.gitlab.io/AMR, https://github.com/msberends/AMR
```

![image](https://user-images.githubusercontent.com/31037261/58460875-bf54df80-812e-11e9-83c0-4e674e5adf15.png)

But when the `URL` field contains git**lab**.com, (which it [actually does](https://gitlab.com/msberends/AMR/blob/master/DESCRIPTION)), the page source is not printed:

```yaml
URL: https://msberends.gitlab.io/AMR, https://gitlab.com/msberends/AMR
```
![image](https://user-images.githubusercontent.com/31037261/58460935-e01d3500-812e-11e9-9ab0-42a8225d585c.png)

The suffix `/blob/master/` also works for GitLab - all full URLs are exactly the same as GitHub, aside from the domain. Any plan to support? Would be great!
And then perhaps also an option in `_pkgdown.yml` to turn this on (default) and off?

**Comment by hadley** [comment] 2020-03-11 20:03
Duplicate of new #1238

**Closed by hadley** 2020-03-11 20:03 UTC
Labels: feature, linking :paperclip:

**Comment by chuxinyuan** [comment] 2020-06-24 11:05
When my source is GitLab, I found that the icon on the generated web page was  GitHub, but the connection was normal and I needed to make some adjustments in docs/index.html. 

` ` ` `
<span class="fab fa fab fa-gitlab fa-lg"></span>
` ` ` `

**Comment by hadley** [comment] 2020-06-24 12:27
@chuxinyuan can you please file a new issue? Commenting on a closed issue is not generally a good way to get results.

**Comment by chuxinyuan** [comment] 2020-06-24 12:55
@hadley Sorry, I will file a new issues.
