### ISSUE TITLE
Print stderr output from pandoc subprocess in build_site()

### ISSUE THREAD

**Issue by jeroen** [r-lib/pkgdown#1167] opened 2019-10-23 10:54 UTC
When `pandoc` fails to render markdown it prints the problems to `stderr`. This gets captured by callr, however it is not used so `build_site()` fails like [this example](https://travis-ci.org/thomasp85/lime/jobs/592943941). 

```
── Building articles ───────────────────────────────────────────────────────────
Writing 'articles/index.html'
Reading 'vignettes/Understanding_lime.Rmd'
Error : callr subprocess failed: pandoc document conversion failed with error 99
Error: callr subprocess failed: callr subprocess failed: pandoc document conversion failed with error 99
Execution halted
Script failed with status 1
```

Because pkgdown usually runs in CI and the problem may be specific to the version of pandoc on the server, this is difficult to debug. 

It would be helpful if `build_site()` would print stderr output from the pandoc process so the user can see pandoc warnings/errors that may cause the rendering to fail.

**Comment by hadley** [comment] 2020-03-10 21:49
I don't think pkgdown does this call? `build_article()` calls `render_rmarkdown()` which calls `rmarkdown::render()`? 

OTOH maybe all that's necessary is to tweak the `quiet` argument somehow?

**Comment by hadley** [comment] 2020-03-11 17:42
Yeah, I think this might just be a duplicate of #952

**Closed by hadley** 2020-03-11 17:42 UTC
Labels: articles :writing_hand:, feature
