### ISSUE TITLE
Reinstall package after updating the documentation

### ISSUE THREAD

**Issue by mllg** [r-lib/pkgdown#718] opened 2018-06-05 15:00 UTC
We encountered a problem where the NAMESPACE file was not updated on the master (which is clearly our fault) which then uncovered some potentially unwanted behavior of `pkgdown`:

- Package is re-installed (https://travis-ci.org/mlr-org/mlr/jobs/388222642#L1199) while building the reference
- NAMESPACE is updated (https://travis-ci.org/mlr-org/mlr/jobs/388222642#L1221), package is re-loaded (not re-installed). 
- `pkgdown` starts a new R session via `callr` to build the html docs. We now get an exception as the new session picks up the package from the file system with the outdated NAMESPACE.

While it is clearly our responsibility to ensure that all functions are properly exported, I believe that working with two different versions of the package is unintended. IMHO `devtools::document()` should be called before re-installing the package.

**Comment by hadley** [comment] 2018-06-05 15:09
It's not reinstalling it, it's just rebuilding the binaries.

But are you using pkgdown 1.1.0? It now re-documents by default.

**Comment by pat-s** [comment] 2018-06-05 19:39
> It's not reinstalling it, it's just rebuilding the binaries.

The problem is that `build_site(document = T)` first (re-)installs the package (with the old NS), then writes the NS and just re-loads the package (which is not enough apparently to pick up the modified NS): https://travis-ci.org/mlr-org/mlr/jobs/388222642. So the "document" step should be called before installing the package.

Interesting: Calling `devtools::document()` in RStudio, first the NS is build and then the package is installed:

```r
devtools::document(roclets=c('rd', 'collate', 'namespace'))

Updating mlr documentation
Loading mlr
Writing NAMESPACE
Documentation completed

==> R CMD INSTALL --no-multiarch --with-keep.source mlr
```


> But are you using pkgdown 1.1.0? It now re-documents by default.

We are using `pkgdown` through `tic` (setting everything up and the final call). Even if its taken from the cache it should be automatically updated. So yes, I assume we are using 1.1 (cannot find it in the travis log for some reason). But in the build I referenced we specifically set `document = TRUE` in `build_site()`: 

https://github.com/mlr-org/mlr/blob/02b7aea1ee4cb185c2d72a4cf2464731d082d251/tic.R#L48

**Comment by mllg** [comment] 2018-06-07 11:42
> It's not reinstalling it, it's just rebuilding the binaries.
> 
> But are you using pkgdown 1.1.0? It now re-documents by default.

Re-document + re-install? Otherwise I still see potential problems with `callr` and its spawned R session.

**Comment by hadley** [comment] 2018-11-06 15:51
Closing in favour of #749 because I think that's the solution.

**Closed by hadley** 2018-11-06 15:51 UTC
