### ISSUE TITLE
`build_article()` fails with large chunk sizes, no errors reported when setting `quiet=FALSE`

### ISSUE THREAD

**Issue by marine-ecologist** [r-lib/pkgdown#2342] opened 2023-09-11 04:56 UTC
# Issue

- `pkgdown::build_articles()` fails with large chunk sizes whereas `rmarkdown::render()` works fine
- article fails to render any code or text beyond the failed chunk  
- **no** errors are reported with build_article(`quiet=FALSE`)

more details:

- reproducible example below
- `sf` object and plotted with `tmap` fails at ~9300000 bytes
- not package specific, reproducible with `leaflet` / `htmlwidget` objects as well as `tmap`
- likely related to related to [this issue](https://github.com/r-lib/pkgdown/issues/2339) 

# example Rmd file below.

Run with:
`pkgdown::build_article("sf-multi-map", quiet=FALSE)` - ❌ 
`rmarkdown::render("vignettes/sf-multi-map.Rmd")` - ✅  

 ````
---
title: "sf multi-map"
output: html_document
---
### runs fine with 1000 rows (1260632 bytes)

` ``{r}

library(sf)
library(tmap)


nc <- st_read(system.file("shape/nc.shp", package="sf"))
merged <- do.call(rbind, rep(list(nc), 10))

object.size(merged)
nrow(merged)

tmap_mode("view") +
   tm_shape(merged) +
   tm_fill(col="NAME", lwd = 0.2) 

   
 ```

### no map with 7500 rows (9331032 bytes)

 ```{r}

 library(sf)
 library(tmap)
 
 
 nc <- st_read(system.file("shape/nc.shp", package="sf"))
 merged <- do.call(rbind, rep(list(nc), 75))
 
 object.size(merged)
 nrow(merged)
 
 tmap_mode("view") +
    tm_shape(merged) +
    tm_fill(col="NAME", lwd = 0.2)


 ```




### No map with two layers of 4000 + 4000 rows:

 ```{r}

library(sf)
library(tmap)


nc <- st_read(system.file("shape/nc.shp", package="sf"))
merged <- do.call(rbind, rep(list(nc), 40))
merged2 <- do.call(rbind, rep(list(nc), 40))

nrow(merged)
nrow(merged2)

tmap_mode("view") +
   tm_shape(merged) +
   tm_fill(col="NAME", lwd = 0.2)  +
  tm_shape(merged2) +
   tm_fill(col="CNTY_", lwd = 0.2) 


   
 ```

**Comment by hadley** [comment] 2023-10-30 16:22
Given that it's probably unlikely you'll want to include a 10 MB file to view a vignette, I think this is unfortunately out of scope for pkgdown. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Closed by hadley** 2023-10-30 16:22 UTC
Labels: bug
